// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj-2JRfLgTk_LJxi9Cppk7i516jPL28yw',
    appId: '1:27915375317:web:cafe19683a966c3724885c',
    messagingSenderId: '27915375317',
    projectId: 'sns-app-2ac97',
    authDomain: 'sns-app-2ac97.firebaseapp.com',
    storageBucket: 'sns-app-2ac97.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpvAvfXYpbXXzJKSykndTCsijmW1sbWhs',
    appId: '1:27915375317:android:4a1d6efa178bbdd024885c',
    messagingSenderId: '27915375317',
    projectId: 'sns-app-2ac97',
    storageBucket: 'sns-app-2ac97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDieDZy-gwWHZz-90sso-GDJras2bA2mlw',
    appId: '1:27915375317:ios:3ba71c6d0f32929024885c',
    messagingSenderId: '27915375317',
    projectId: 'sns-app-2ac97',
    storageBucket: 'sns-app-2ac97.appspot.com',
    iosClientId: '27915375317-gsulp36ff66g1u4j6jv30jfa5jdvqiiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.sns',
  );
}
